Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [ ]:
import numpy as np

In [ ]:
#  python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)



# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 

[1 2 3 4 5]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
def create_random_array():
    """
    Create a NumPy array with random values of shape [3,4]
    """
    return np.random.rand(3, 4)
    # Example usage
my_array = create_random_array()
print(my_array)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def create_zero_array():
    """
    Create a NumPy array with all elements initialized as zero of shape [3,4]
    """
    return np.zeros((3, 4))

# Example usage
my_array = create_zero_array()
print(my_array)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4] 
def create_ones_array():
    """
    Create a NumPy array with all elements initialized as one of shape [3,4]
    """
    return np.ones((3, 4))

# Example usage
my_array = create_ones_array()
print(my_array)

[[0.53809393 0.88175423 0.87365257 0.32228238]
 [0.1951354  0.4966979  0.56293927 0.43299562]
 [0.01459085 0.67752021 0.07550661 0.08835605]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
import numpy as np

def create_range_array(start, stop, step):
    """
    Create a NumPy array containing a range of evenly spaced intervals
    """
    return np.arange(start, stop, step)

# Example usage
my_array = create_range_array(0, 10, 2)
print(my_array)

# Hint : Use np.arange or np.linspace

[0 2 4 6 8]


### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
   
def perform_arithmetic_operations(a, b):
    """
    Perform arithmetic operations (addition, subtraction, multiplication, and division) on two NumPy arrays
    """
    # Element-wise addition
    c = a + b
    
    # Element-wise subtraction
    d = a - b
    
    # Element-wise multiplication
    e = a * b
    
    # Element-wise division
    f = np.divide(a, b)
    
    return c, d, e, f

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
perform_arithmetic_operations(a, b)



(array([[ 7, 22, 26],
        [99, 40, 82],
        [62, 56, 80]]),
 array([[-15, -10, -10],
        [-81, -34, -80],
        [-60, -40, -70]]),
 array([[-44,  96, 144],
        [810, 111,  81],
        [ 61, 384, 375]]),
 array([[-0.36363636,  0.375     ,  0.44444444],
        [ 0.1       ,  0.08108108,  0.01234568],
        [ 0.01639344,  0.16666667,  0.06666667]]))

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
def sum_along_axis_0(a):
    """
    Get the sum of an array 'a' along axis=0
    """
    # Sum along axis=0
    sum_a = np.sum(a, axis=0)
    
    return sum_a
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
sum_along_axis_0(a)
     

# Write a NumPy function to get the sum of the array 'a' along axis=1 
def sum_along_axis_1(a):
    """
    Get the sum of an array 'a' along axis=1
    """
    # Sum along axis=1
    sum_a = np.sum(a, axis=1)
    
    return sum_a
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
sum_along_axis_1(a)


array([10, 13, 14])

In [ ]:
# Write a NumPy function to reverse the array 'a' 
def reverse_array(a):
    """
    Reverse the array 'a'
    """
    # Reverse the array using np.flip()
    reversed_a = np.flip(a)
    
    return reversed_a
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
reverse_array(a)

# Write a NumPy function to reverse the array 'a' along axis=0

def reverse_array_axis_0(a):
    """
    Reverse the array 'a' along axis=0
    """
    # Reverse the array along axis=0 using np.flip()
    reversed_a = np.flip(a, axis=0)
    
    return reversed_a
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
reverse_array_axis_0(a)

# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_array_axis_1(a):
    """
    Reverse the array 'a' along axis=1
    """
    # Reverse the array along axis=1 using np.flip()
    reversed_a = np.flip(a, axis=1)
    
    return reversed_a
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
reverse_array_axis_1(a)


array([[ 8,  6, -4],
       [ 1,  3,  9],
       [ 5,  8,  1]])

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 
def sort_array(a):
    """
    Sort the array 'a'
    """
    # Sort the array using np.sort()
    sorted_a = np.sort(a)
    
    return sorted_a
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
sort_array(a)

# Write a NumPy function to sort the array 'a' along axis=0
def sort_array_axis_0(a):
    """
    Sort the array 'a' along axis=0
    """
    # Sort the array along axis=0 using np.sort()
    sorted_a = np.sort(a, axis=0)
    
    return sorted_a
    a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
sort_array_axis_0(a)


# Write a NumPy function to sort the array 'a' along axis=1
def sort_array_axis_1(a):
    """
    Sort the array 'a' along axis=1
    """
    # Sort the array along axis=1 using np.sort()
    sorted_a = np.sort(a, axis=1)
    
    return sorted_a
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
sort_array_axis_1(a)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort_array_descending_axis_0(a):
    """
    Sort the array 'a' in descending order along axis=0
    """
    # Sort the array in descending order along axis=0 using np.sort() and reverse the axis
    sorted_a_descending = np.sort(a, axis=0)[::-1]
    
    return sorted_a_descending
a = np.array([[-4,6,8],[9,3,1],[1,8,5]])
sort_array_descending_axis_0(a)


array([[ 9,  8,  8],
       [ 1,  6,  5],
       [-4,  3,  1]])

In [ ]:
# Write a NumPy function to argsort the array along axis=0
def argsort_axis0(arr):
    return np.argsort(arr, axis=0)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
argsort_axis0(a)

# Write a NumPy function to argsort the array along axis=1
def argsort_axis1(arr):
    return np.argsort(arr, axis=1)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
argsort_axis1(a)


array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenate_arrays(a, b):
    return np.concatenate((a, b))
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

concatenate_arrays(a, b)
         


# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 
def concatenate_arrays_axis0(a, b):
    return np.concatenate((a, b), axis=0)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

concatenate_arrays_axis0(a, b)
         

# Note: You can do the same function using stacking, discover and try that :)


array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
def get_num_dimensions(arr):
    return arr.ndim
arr = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
get_num_dimensions(a)


# Write a NumPy function to get the Shape of the array 
def get_shape(arr):
    return arr.shape 
arr = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
get_shape(arr)

# Write a NumPy function to get the Size of the array
def get_size(arr):
    return arr.size
arr = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
get_size(arr)

9

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape_array(a):
    return a.reshape(1, 9)
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
reshape_array(a)

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 
def add_new_axis(a):
    return np.expand_dims(a, axis=0)
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
add_new_axis(a)   

# Note : Show atleast two different ways of doing this 


array([[[4, 6, 8],
        [9, 3, 1],
        [1, 8, 5]]])

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
import numpy as np

def index_and_slice(arr):
    # Indexing by an integer
    print(arr[0])
    
    # Indexing by a tuple
    print(arr[0, 1])
    
    # Slicing using range
    print(arr[0:2, 1:3])
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
index_and_slice(a)




[4 6 0]
6
[[6 0]
 [3 1]]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
import numpy as np

def select_greater_than_4(arr):
    return arr[arr > 4]
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
print(select_greater_than_4(a))


# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
import numpy as np
def select_greater_than_4_and_divisible_by_2(arr):
    return arr[(arr > 4) & (arr % 2 == 0)]

a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
print(select_greater_than_4_and_divisible_by_2(a))



[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
import numpy as np

def copy_and_increment(arr):
    copy_arr = arr.copy()  # make a copy of the input array
    copy_arr += 1  # increment all elements of the copy by 1
    return copy_arr
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
result = copy_and_increment(a)
print(result)




[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd

def drop_missing_values(df):
    return df.dropna()
df = pd.DataFrame({'A': [1, 2, 3, None, 5], 'B': [4, 5, None, 7, 8]})
result = drop_missing_values(df)
print(result)




     A    B
0  1.0  4.0
1  2.0  5.0
4  5.0  8.0


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
import pandas as pd

def compute_correlation(df):
    return df.iloc[:, 0:2].corr()



In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import pandas as pd

def stats_column3(df):
    col3 = df.iloc[:, 2] # select column 3
    return {'mean': col3.mean(), 'median': col3.median(), 'std_dev': col3.std()}
df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [2, 4, 6, 8, 10], 'C': [3, 6, 9, 12, 15]})
result = stats_column3(df)
print(result)




{'mean': 9.0, 'median': 9.0, 'std_dev': 4.743416490252569}


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
import numpy as np
import pandas as pd

def add_volume_column(df):
    petal_length = df.iloc[:, 2] # select petal_length column
    sepal_length = df.iloc[:, 0] # select sepal_length column
    volume = (np.pi * petal_length * sepal_length**2) / 3 # calculate volume
    df['volume'] = volume # add volume as a new column in the DataFrame
    return df

# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np

def ones_like_x(x):
   ones_array = np.ones_like(x)
   return ones_array
x = np.arange(4, dtype=np.int64)
a = ones_like_x(x)   
print(a)
     


[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
import numpy as np

def split_x():
    x = np.arange(1,10) 
    split_array = np.split(x,[4,6])
    return split_array
split_array = split_x()  
print(split_array)
     

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
def max_min_indices_x():
    x = np.random.uniform(0, 10, size=(2, 5))
    max_v = np.amax(x, axis=1)
    max_i = np.argmax(x, axis=1)
    min_v = np.amin(x, axis=1)
    min_i = np.argmin(x, axis=1)
    return max_v, max_i, min_v, min_i
max_v, max_i, min_v, min_i = max_min_indices_x()
print("Max values along the second axis",max_v,)   
print("Indices of Max values along the second axis", max_i)
print("Max values along the second axis", min_v)
print("Indices of Max values along the second axis", min_i)

Max values along the second axis [7.44765029 4.9892932 ]
Indices of Max values along the second axis [3 0]
Max values along the second axis [0.94996566 0.40911022]
Indices of Max values along the second axis [0 1]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])

count_unique_species = iris['species'].nunique()

print(count_unique_species)


3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:


import pandas as pd
import numpy as np

# Load the iris dataset from URL
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])

# Define the bins and corresponding labels
bins = [0, 3, 5, np.inf]
labels = ['small', 'medium', 'large']

# Create a new column with the binned petal length values
iris['petal_length_bin'] = pd.cut(iris['petallength'], bins=bins, labels=labels)

# Print the first 10 rows of the resulting dataframe
print(iris.head(10))


   sepallength  sepalwidth  petallength  petalwidth      species  \
0          5.1         3.5          1.4         0.2  Iris-setosa   
1          4.9         3.0          1.4         0.2  Iris-setosa   
2          4.7         3.2          1.3         0.2  Iris-setosa   
3          4.6         3.1          1.5         0.2  Iris-setosa   
4          5.0         3.6          1.4         0.2  Iris-setosa   
5          5.4         3.9          1.7         0.4  Iris-setosa   
6          4.6         3.4          1.4         0.3  Iris-setosa   
7          5.0         3.4          1.5         0.2  Iris-setosa   
8          4.4         2.9          1.4         0.2  Iris-setosa   
9          4.9         3.1          1.5         0.1  Iris-setosa   

  petal_length_bin  
0            small  
1            small  
2            small  
3            small  
4            small  
5            small  
6            small  
7            small  
8            small  
9            small  


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
import pandas as pd

# load iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
iris = pd.read_csv(url, names=names)

# find the most frequent value of petal length
most_frequent_petal_length = iris['petal-length'].mode()[0]

print("The most frequent value of petal length is:", most_frequent_petal_length)



The most frequent value of petal length is: 1.5
