Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr = np.arange(1,6)
arr
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:

arr2=np.random.rand(12).reshape(3,4)
arr3=np.zeros(12).reshape(3,4)
arr4=np.ones(12).reshape(3,4)
print(arr2)
print(arr3)
print(arr4)


[[0.44664952 0.24492037 0.7022077  0.94345155]
 [0.454394   0.50669913 0.92044008 0.91524625]
 [0.00496768 0.25119384 0.11380817 0.67402   ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
a=np.arange(10,21,2)
print(a)
# Hint : Use np.arange or np.linspace

[10 12 14 16 18 20]


### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
a=np.array([[3,4],[4,5]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 8 10]
 [11 13]]
[[-2 -2]
 [-3 -3]]
[[15 24]
 [28 40]]
[[0.6        0.66666667]
 [0.57142857 0.625     ]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
a=np.array([[23,45],[90,57]])
print(a.sum(axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1 
print(a.sum(axis=1))

[113 102]


In [ ]:
# Write a NumPy function to reverse the array 'a' 
a=np.array([[9,8],[7,9]])
b=np.flip(a)
print(b)
# Write a NumPy function to reverse the array 'a' along axis=0
a=np.array([[9,8],[7,9]])
b=np.flip(a,axis=0)
print(b)
# Write a NumPy function to reverse the array 'a' along axis=1
a=np.array([[9,8],[7,9]])
b=np.flip(a,axis=1)
print(b)

[[9 7]
 [8 9]]
[[7 9]
 [9 8]]
[[8 9]
 [9 7]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 
arr = np.sort(a)
print(arr)
# Write a NumPy function to sort the array 'a' along axis=0
arr0 = np.sort(a,axis=0)
print(arr0)
# Write a NumPy function to sort the array 'a' along axis=1
arr1 = np.sort(a,axis=1)
print(arr1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
arr2 = -np.sort(-a,axis=0)
print(arr2)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
arr = np.argsort(a,axis=0)
print(arr)
# Write a NumPy function to argsort the array along axis=1
arr1 = np.argsort(a,axis=1)
print(arr1)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
arr = np.concatenate((a,b))
print(arr)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
arr1 = np.concatenate((a,b),axis=0)
print(arr1)
# Note: You can do the same function using stacking, discover and try that :)
arr2 = np.stack((a,b))
print(arr2)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[[-4  6  8]
  [ 9  3  1]
  [ 1  8  5]]

 [[11 16 18]
  [90 37 81]
  [61 48 75]]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array  
print(arr.shape)
# Write a NumPy function to get the Size of the array
print(arr.size)

2
(6, 3)
18


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
newarr = a.reshape(1,9)
print(newarr)

[[-4  6  8  9  3  1  1  8  5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 
#first method
arr = a[np.newaxis, :]
print(arr)
#second method
arr1=np.expand_dims(a, axis=0)
print(arr1)

[[[[4]
   [6]
   [0]]

  [[0]
   [3]
   [1]]

  [[1]
   [8]
   [5]]]]
[[[[4]
   [6]
   [0]]

  [[0]
   [3]
   [1]]

  [[1]
   [8]
   [5]]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
element = a[1]
print("second element:",element)
arr = a[0,2]
print("element at index [0,2]:",arr)
s_arr = a[0:2,1:2]
print("sliced array:",s_arr)

second element: [[0]
 [3]
 [1]]
element at index [0,2]: [0]
sliced array: [[[6]]

 [[3]]]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
def req_value(a,y):
  x= a>y
  ans=a[x]
  return ans
required=req_value(a,4)
print(required) 
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def req_value(a):
  x= a>4
  y= a%2==0
  z= np.logical_and(x,y)
  ans=a[z]
  return ans
required=req_value(a)
print(required)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
arr = np.copy(a)
arr = arr+1
print(arr)


[[[5]
  [7]
  [1]]

 [[1]
  [4]
  [2]]

 [[2]
  [9]
  [6]]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd
def droprows(df):
       df_dropped = df.dropna()
       return df_dropped
df=pd.DataFrame(iris_2d)
df_dropped = droprows(df)
print(df_dropped)      

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
def correlation(df):
  x = df.iloc[:, 0:2]
  cor=x.corr()
  return cor
  df=pd.DataFrame(iris_2d)
cor=correlation(df)
print(cor)

          0         1
0  1.000000 -0.109369
1 -0.109369  1.000000


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import pandas as pd
def stats(df,column):
  mean=df[column].mean()
  median=df[column].median()
  std_dev=df[column].std()
  return mean,median,std_dev
df = pd.DataFrame(iris_2d)
mean,median,std_dev = stats(df, 3)
print("Mean, Median, Std_dev respectively are:", mean,median,std_dev)

Mean, Median, Std_dev respectively are: 1.1986666666666668 1.3 0.7631607417008411


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import pandas as pd
def stats(df,column):
  mean = df[column].mean()
  median = df[column].median()
  std_dev = df[column].std()
  return mean,median,std_dev
df = pd.DataFrame(iris_2d)
mean,median,std_dev= stats(df,3)
print("Mean, Median, Std_dev respectively are:", mean,median,std_dev)


Mean, Median, Std_dev respectively are: 1.1986666666666668 1.3 0.7631607417008411


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np
x = np.arange(4,dtype=np.int64)
y = np.ones_like(x)
print(y)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x= np.arange(1,10)
a= np.split(x,[4,6])
print(a)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np
arr = np.random.randint(0,10, size=(2,5))
print("maximum values of array along axis=1:", np.max(arr, axis=1))
print("minimum values of array along axis=1:", np.min(arr, axis=1))
print("indices of max values along axis=1:", np.argmax(arr, axis=1))
print("indices of min values along axis=1:", np.argmin(arr, axis=1))

maximum values of array along axis=1: [8 6]
minimum values of array along axis=1: [0 1]
indices of max values along axis=1: [2 3]
indices of min values along axis=1: [3 4]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd
def count_unique(data):
  unique = data.nunique()
  return unique
data = pd.DataFrame(iris)
x = count_unique(data)
print(x)

0    35
1    23
2    43
3    22
4     3
dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
import pandas as pd
def binpetal_length(data):
  data['petal_length_bin']=pd.cut(data['petallength'], bins=[0,3,5, float('inf')], labels=['small','medium','large'], right=False)
  return data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])
iris_2d_binned = binpetal_length(iris_2d)
print(iris_2d_binned)

     sepallength  sepalwidth  petallength  petalwidth         species  \
0            5.1         3.5          1.4         0.2     Iris-setosa   
1            4.9         3.0          1.4         0.2     Iris-setosa   
2            4.7         3.2          1.3         0.2     Iris-setosa   
3            4.6         3.1          1.5         0.2     Iris-setosa   
4            5.0         3.6          1.4         0.2     Iris-setosa   
..           ...         ...          ...         ...             ...   
145          6.7         3.0          5.2         2.3  Iris-virginica   
146          6.3         2.5          5.0         1.9  Iris-virginica   
147          6.5         3.0          5.2         2.0  Iris-virginica   
148          6.2         3.4          5.4         2.3  Iris-virginica   
149          5.9         3.0          5.1         1.8  Iris-virginica   

    petal_length_bin  
0              small  
1              small  
2              small  
3              small  
4       

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
import pandas as pd
def frequent_petal_length(url):
    iris = pd.read_csv(url, header=None, names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'))
    most_frequent_value = iris['petallength'].mode().values[0]
    return most_frequent_value
    url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
most_frequent_value = frequent_petal_length(url)
print("Most frequent value of petal length:", most_frequent_value)

Most frequent value of petal length: 1.5
