Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [ ]:
import numpy as np

In [4]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
list1 = [i for i in range(1,6)]
print(list1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
list2 = [[j for j in range(3*i+1,3*i+4)] for i in range(3)]
print(list2)

[1, 2, 3, 4, 5]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
# Write a NumPy function to create an array with random values of shape [3,4]
print(np.random.randint(1,10,(3,4)))
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
print(np.zeros((3,4)))
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
print(np.ones((3,4)))

[[8 4 3 5]
 [9 1 8 2]
 [9 4 6 5]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Basic array operations
- algebraic operations 
- logical operations

In [8]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [9]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [10]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
print(np.sum(a,axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1 
print(np.sum(a,axis=1))

[ 6 17 14]
[10 13 14]


In [11]:
# Write a NumPy function to reverse the array 'a' 
print(np.flip(a))
# Write a NumPy function to reverse the array 'a' along axis=0
print(np.flip(a,axis=0))
# Write a NumPy function to reverse the array 'a' along axis=1
print(np.flip(a,axis=1))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [12]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [13]:
# Write a NumPy function to sort the array 'a' 
print(np.flip(a,axis=1))
# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a,axis=0))
# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a,axis=1))
# Write a NumPy function to sort the array 'a' in descending order along axis=0
print(np.flip(np.sort(a,axis=0),axis=0))

[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [14]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a,axis=0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a,axis=1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [15]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b),axis=1))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b),axis=0))
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [16]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [17]:
# Write a NumPy function to get the Number of dimensions
print(len(a.shape))
# Write a NumPy function to get the Shape of the array  
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [18]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(np.reshape(a,(1,9)))

[[4 6 8 9 3 1 1 8 5]]


In [19]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 
print(np.reshape(a,(1,3,3)))
print(np.expand_dims(a,axis=0))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
import numpy as np
arr=np.arange(1,10,2)
arr1=arr[np.array([4,0,2,-1,-2])]
print(arr1)
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
X = np.copy(a)
print(X+1)

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [24]:
import pandas as pd
# Write a Pandas function to drop rows that contain a missing value. 
DF = pd.DataFrame(iris_2d)
DF.dropna()

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [25]:
# Write a Pandas function to find the correlation between the first two columns.
print(DF[0].corr(DF[1]))

-0.10936924995064937


In [26]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print('',DF[3].mean(),'\n',DF[3].median(),'\n',DF[3].std())

 1.1986666666666668 
 1.3 
 0.7631607417008411


In [27]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
DF['New Column']=[DF[2][i]*3.14*DF[0][i]*DF[0][i]/3 for i in range(len(DF.index))]
DF

0    1    2    3  New Column
0    5.1  3.5  1.4  0.2   38.113320
1    4.9  3.0  1.4  0.2   35.182653
2    4.7  3.2  1.3  0.2   30.057127
3    4.6  3.1  1.5  0.2   33.221200
4    5.0  3.6  1.4  0.2   36.633333
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.321307
146  6.3  2.5  5.0  1.9  207.711000
147  6.5  3.0  5.2  2.0  229.952667
148  6.2  3.4  5.4  2.3  217.262880
149  5.9  3.0  5.1  1.8  185.815780

[150 rows x 5 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
print(np.ones(4,dtype=np.int64))

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [3]:
import numpy as np
a = np.split(np.arange(1,10),[4,6])
print(a)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [44]:
import numpy as np
Z= np.arange(10).reshape(2,5)
print(Z)
rslt1 = np.amax(Z, 1)
print("\nMaximum Value:",rslt1)
rslt2 = np.amin(Z, 1)
print("\nMinimum Value:",rslt2)

[[0 1 2 3 4]
 [5 6 7 8 9]]

Maximum Value: [4 9]

Minimum Value: [0 5]


### Pandas

Run the following load command and solve the following questions

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [32]:
DF = pd.DataFrame(iris)
DF1=DF.drop_duplicates(keep='first')
len(DF.index)-len(DF1.index)

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [33]:
def sort(I):
  if I<3:
    return 'small'
  elif I>5:
    return 'large'
  else:
    return 'medium'
[sort(eval(DF[2][i])) for i in range(len(DF.index))]

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medi

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [34]:
eval(DF[2].mode()[0])

1.5