Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [2]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
list=[1,2,3,4,5]
p=np.array(list)
print(list)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
list_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(list_2d) 

[1, 2, 3, 4, 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Write a NumPy function to create an array with random values of shape [3,4]
def randoms(a,b):
  return np.random.rand(a,b)

r=randoms(3,4)
print(r)
# write a NumPy function to create an array with all elements initialized as zeros of shape [3,4]
def zero(a,b):
  return np.zeros((a,b))
p=zero(3,4)
print(p)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def inti_as_one(a,b,i):
 return  np.full((a,b),i)
p=inti_as_one(3,3,1)
print(p)

[[0.61625833 0.23676914 0.09112502 0.54811057]
 [0.28316909 0.27399935 0.90539212 0.27328339]
 [0.34687705 0.12597381 0.23953489 0.04645401]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
import numpy as np
def evenly_spaced(int,end,interval) : 
  return np.linspace(int,end,interval)

lsp=evenly_spaced(1,10,5)

print(lsp)

[ 1.    3.25  5.5   7.75 10.  ]


### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'

A=np.add(a,b)
B=np.subtract(a,b)
C=np.multiply(a,b)
D=np.divide(a,b)
print(A)
print(B)
print(C)
print(D)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
def sum_along_axis(a,i) :
  return np.sum(a,axis=i)
sum=sum_along_axis(a,0)
print(sum)

# Write a NumPy function to get the sum of the array 'a' along axis=1 
def sum_along_axis(a,i) :
  return np.sum(a,axis=i)
sum=sum_along_axis(a,1)
print(sum)


[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a' 
def reversed(a): 
  return np.flip(a)
reversed1=reversed(a)
print(reversed1)
# Write a NumPy function to reverse the array 'a' along axis=0
def reversing_along_axis0(a,axis=0):
  return np.flip(a,axis=0)
  reversal0=reversing_along_axis0(a,axis=0)
print(reversal0)
# Write a NumPy function to reverse the array 'a' along axis=1
def reversing_along_axis1(a,axis=1):
  return np.flip(a,axis=1)
  reversal1=reversing_along_axis1(a,axis=1)
print(reversal1)


[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 
def sorting_array(arr):
  return np.sort(arr)
sorted=sorting_array(a)
print(sorted)
# Write a NumPy function to sort the array 'a' along axis=0
def sorting_array(arr,axis):
  return np.sort(arr,axis)
sorted0=sorting_array(a,axis=0)
print(sorted0)

# Write a NumPy function to sort the array 'a' along axis=1
def sorting_array_along_axis1(arr,axis):
  return np.sort(arr,axis)
sorted_along_axis1=sorting_array_along_axis1(a,axis=1)
print(sorted)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
sorted0=np.sort(a,axis=0)
des=np.flip(sorted0,axis=0)
print(des)
sorted=np.sort(a)



[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
def argsort_along_axis0(a,axis):
  return np.argsort(a,axis)
arg=argsort_along_axis0(a,axis=0)
print(arg)
# Write a NumPy function to argsort the array along axis=1
array=a
def argsort_along_axis1(arr,axis):
  return np.argsort(array,axis)
arg1=argsort_along_axis1(array,axis=1)
print(arg1)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenating(arr1,arr2):
  return np.concatenate((arr1,arr2))
  arr1=a
  arr2=b
con=concatenating(a,b)
print(con)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concatenating(arr1,arr2,axis):
  return np.concatenate((arr1,arr2),axis)
  arr1=a
  arr2=b
con0=concatenating(a,b,0)
print(con0)


# Note: You can do the same function using stacking, discover and try that :)
con1=np.stack((a,b),axis=0)
print(con1)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[[-4  6  8]
  [ 9  3  1]
  [ 1  8  5]]

 [[11 16 18]
  [90 37 81]
  [61 48 75]]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
import numpy as np


In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
import numpy as np

def num_dimensions(arr):
  return np.ndim(arr)

Number = num_dimensions(a)
print(Number)

# Write a NumPy function to get the Shape of the array  
def shapeofarray(array):
  return np.shape(array)

shap=shapeofarray(a)
print(shap)
# Write a NumPy function to get the Size of the array
def sizeof(array):
  return np.size(array)
  
arraysize=sizeof(a)
print(arraysize)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshaping(array,rows,columns):
  return np.reshape(array,(rows,columns))

reshaped_array=reshaping(a,1,9) 

print(reshaped_array)

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 
def expansionof_dimension(array,axis):
  return np.expand_dims(array,axis)

print("by expansion ")
array_with_new_axis=expansionof_dimension(a,axis=0)
print(array_with_new_axis)

print("by new axis method")
def expansion_by_new_axis(array):

 return a[np.newaxis,:]


array_newaxis= expansion_by_new_axis(a)
print(array_newaxis)
# Note that Show atleast two different ways of doing this 


by expansion 
[[[4 6 0]
  [0 3 1]
  [1 8 5]]]
by new axis method
[[[4 6 0]
  [0 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
import numpy as np

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
#write a numpy function to indexing and sclicing the array like in python list.
def indexing_by_int(a,i):
  return  a[i]
using_index= indexing_by_int(a,1)
print("this is indexing by integer:",using_index)

def indexing_by_tuple(array,i,j):
 return array[i][j]
using_tuple= indexing_by_tuple(a,1,2)
print("by tuple:",using_tuple)

def indexing_by_slicing(array,i,j,k,l):
 return array[i:j, k:l]
using_slicing= indexing_by_slicing(a,1,3,0,2)
print(" by sclicing:",using_slicing)


def index_array_by_range(arr, start, end):
    return arr[start:end]
result = index_array_by_range(a, 1, 3)
print("indexing by range:", result)

#show it by indexing using integer,by tuple,and range


this is indexing by integer: [0 3 1]
by tuple: 1
 by sclicing: [[0 3]
 [1 8]]
indexing by range: [[0 3 1]
 [1 8 5]]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
def greator_value_in(array):
  return array[np.where(a>4)]

vals=greator_value_in(a)
print(vals)

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def even_and_greatorthan4(array):
  return array[np.where((array>4) & (array%2==0))]
  
vals2=even_and_greatorthan4(a)
print(vals2)


[6 8 9 8 5]
[6 8 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def arr(array,i):
  return np.empty_like(a) + i
  a1=arr(a,1)
  
  print(a1)

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
import numpy as np

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
import pandas as pd

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
def func(arr):
  return arr.dropna()

df=pd.DataFrame(iris_2d)
k=func(df)
print(k)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
df[0].corr(df[1])


-0.10936924995064937

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import numpy as np
import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])


df = pd.DataFrame(iris_2d, columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth'])


def calculate_mean(data):
    return data.mean()

def calculate_median(data):
    return data.median()

def calculate_std_dev(data):
    return data.std()


mean = calculate_mean(df['petallength'])
median = calculate_median(df['petallength'])
std_dev = calculate_std_dev(df['petallength'])

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)



Mean: 3.758666666666666
Median: 4.35
Standard Deviation: 1.7644204199522626


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import pandas as pd
import numpy as np
from math import pi

def add_volume_column(data):
   volume = (pi * data['petallength'] * data['sepallength']**2) / 3

   data['volume'] = volume
   return data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])

iris_2d_with_volume = add_volume_column(iris_2d)

print(iris_2d_with_volume)

     sepallength  sepalwidth  petallength  petalwidth         species  \
0            5.1         3.5          1.4         0.2     Iris-setosa   
1            4.9         3.0          1.4         0.2     Iris-setosa   
2            4.7         3.2          1.3         0.2     Iris-setosa   
3            4.6         3.1          1.5         0.2     Iris-setosa   
4            5.0         3.6          1.4         0.2     Iris-setosa   
..           ...         ...          ...         ...             ...   
145          6.7         3.0          5.2         2.3  Iris-virginica   
146          6.3         2.5          5.0         1.9  Iris-virginica   
147          6.5         3.0          5.2         2.0  Iris-virginica   
148          6.2         3.4          5.4         2.3  Iris-virginica   
149          5.9         3.0          5.1         1.8  Iris-virginica   

         volume  
0     38.132652  
1     35.200498  
2     30.072372  
3     33.238050  
4     36.651914  
..          ...

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
y=np.arange(1,5,dtype=np.int64)
print(y)

[1 2 3 4]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.arange(1,10)
y=x[0:4]
z=x[4:6]
a=x[6:9]
x=[y,z,a]
print(x)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
array=np.random.rand(2,5)*10
print("Array is:",array)

def max_value(x):
  return np.amax(x,axis=1)
A=max_value(array)
def min_value(x):
  return np.amin(x,axis=1)
B=min_value(array)
def max_indices(x):
  return np.argmax(x,axis=1)
C=max_indices(array)
def min_indices(x):
  return np.argmin(x,axis=1)
D=min_indices(array)
print(A)
print(B)
print(C)
print(D)

Array is: [[3.15995752 3.3450931  1.60489283 2.13685289 1.21362363]
 [4.25737583 8.37000817 0.89396868 9.38034001 1.46282762]]
[3.3450931  9.38034001]
[1.21362363 0.89396868]
[1 3]
[4 2]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
dp=pd.DataFrame(iris)
unique_speices=dp.nunique()

print(unique_speices)

0    35
1    23
2    43
3    22
4     3
dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
import numpy as np
import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Creating a DataFrame from the iris_2d array
df = pd.DataFrame(iris_2d, columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth'])

# Binning the petal length column
bins = [0, 3, 5, np.inf]
labels = ['small', 'medium', 'large']
df['petal_length_category'] = pd.cut(df['petallength'], bins=bins, labels=labels)

# Getting the resulting text array
result_array = df['petal_length_category'].values

print(result_array)


['small', 'small', 'small', 'small', 'small', ..., 'large', 'medium', 'large', 'large', 'large']
Length: 150
Categories (3, object): ['small' < 'medium' < 'large']


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
import numpy as np
import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Creating a DataFrame from the iris array
df = pd.DataFrame(iris, columns=names)

# Cleaning the petal length column
df['petallength'] = df['petallength'].str.decode('utf-8').str.strip()

# Finding the most frequent value of petal length
most_frequent_petal_length = df['petallength'].value_counts().idxmax()

print("Most frequent value of petal length:", most_frequent_petal_length)


Most frequent value of petal length: 1.5
