Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr1 = np.array([1,2,3,4,5])
print(arr1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr1 = np.random.randint(150 , size = (3,4))

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr2 = np.zeros([3,4])

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr3 = np.ones([3,4])

In [4]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
arr6 = np.arange(5)
print(arr6)


[0 1 2 3 4]


### Basic array operations
- algebraic operations 
- logical operations

In [5]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [6]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
np.add(a,b)

array([[ 7, 22, 26],
       [99, 40, 82],
       [62, 56, 80]])

In [7]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
arr1 = np.sum(a, axis = 0)

# Write a NumPy function to get the sum of the array 'a' along axis=1 
arr2 = np.sum(a, axis = 1)


In [8]:
# Write a NumPy function to reverse the array 'a' 
arr1 = np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
arr2 = np.flip(a , axis = 0)

# Write a NumPy function to reverse the array 'a' along axis=1
arr3 = np.flip(a , axis = 1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [9]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [10]:
# Write a NumPy function to sort the array 'a' 
arr1 = np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
arr2 = np.sort(a , axis = 0)

# Write a NumPy function to sort the array 'a' along axis=1
arr3 = np.sort(a , axis = 1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
arr4 = np.sort(a, axis = 0)[::-1]


In [11]:
# Write a NumPy function to argsort the array along axis=0
arr1 = np.argsort(a, axis = 0)

# Write a NumPy function to argsort the array along axis=1
arr2 = np.argsort(a, axis = 1)



In [12]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
arr1 = np.concatenate((a,b) , axis = 1)
#OR
arr1 = np.hstack((a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
arr2 = np.concatenate((a,b) , axis = 0)
#OR
arr2 = np.vstack((a,b))

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [13]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [14]:
# Write a NumPy function to get the Number of dimensions
a.ndim

# Write a NumPy function to get the Shape of the array  
a.shape

# Write a NumPy function to get the Size of the array
a.size


9

In [15]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a.reshape(1,9)

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [16]:
# Write a NumPy function to add a new axis to the array 'a' 
a.reshape(3,3,1)
#OR
a[:,:,np.newaxis]

# Note : Show atleast two different ways of doing this 


array([[[4],
        [6],
        [8]],

       [[9],
        [3],
        [1]],

       [[1],
        [8],
        [5]]])

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [17]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [18]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists

#prints first two elements of array a
print(a[range(2)])

#prints 3rd element of 2nd array
tup = (1,2)
print(a[tup])

#prints the third element in first dimension ( third array )
print(a[2])

# Show all three - indexing by a integer, indexing by a tuple, using range


[[4 6 0]
 [0 3 1]]
1
[1 8 5]


In [19]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
cond1 = [a > 4]
choice = [a]

arr1 = np.select(cond1,choice, default = None)


# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
cond2 = [a%2 == 0]

arr2 = np.select(cond1 and cond2,choice,default = None)


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b = a.copy()
b = b+1

print(b)



[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [23]:
import pandas as pd
# Write a Pandas function to drop rows that contain a missing value. 
df = pd.DataFrame(iris_2d)

df = df.dropna()
df.head

<bound method NDFrame.head of        0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]>

In [24]:
# Write a Pandas function to find the correlation between the first two columns.
corr = df[0].corr(df[1])
corr


-0.10936924995064937

In [25]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df[2].mean()
df[2].median()
df[2].std()

1.7644204199522626

In [26]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

volume = (3.14*df[2]*df[0]**2)/3
df['volume'] = volume


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [36]:
np.ones(4 , dtype=np.int64)

array([1, 1, 1, 1])

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [28]:
x = [1,2,3,4,5,6,7,8,9]
arr1, arr2 ,arr3  = np.split(x,[4,6], axis = 0)


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [29]:
x = np.random.randint(0,10,size = (2,5))
print(x)

print("Maximum values:",np.amax(x , axis = 1),"Indices of Maximum values :",np.argmax(x , axis = 1))
print("Minimum values:",np.amin(x , axis = 1),"Indices of Minimum values :",np.argmin(x , axis = 1))


[[3 4 0 3 3]
 [2 7 0 4 1]]
Maximum values: [4 7] Indices of Maximum values : [1 1]
Minimum values: [0 0] Indices of Minimum values : [2 2]


### Pandas

Run the following load command and solve the following questions

In [30]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [74]:
iris = pd.DataFrame(iris, columns = names)

print(iris.nunique()['species'])


3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [75]:
bins = [0, 3, 5, 10]
labels = ['small','medium','large']

col = (iris['petallength'].astype(str)).str.slice(2,-1).astype(float)

iris['Size'] = pd.cut(x = col, bins = bins, labels=labels)

iris


sepallength sepalwidth petallength petalwidth            species    Size
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'   small
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'   small
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'   small
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'   small
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'   small
..          ...        ...         ...        ...                ...     ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'   large
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'  medium
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'   large
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'   large
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'   large

[150 rows x 6 columns]

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [76]:
iris['petallength'].median()


4.35