Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [37]:
import numpy as np
import math as mt

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr = np.array([1,2,3,4,5])
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
narr = np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(narr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
# Write a NumPy function to create an array with random values of shape [3,4]
from numpy import random 
marr = random.randint(100,size=(3,4))

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
nut = np.zeros([3,4],dtype=int)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
luns = np.ones([3,4],dtype=int)

In [ ]:

# Write a NumPy function to create an array containing a range of evenly spaced intervals
q= np.linspace(4,8,num=8,retstep=True)

# Hint : Use np.arange or np.linspace

### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
res1= a + b
res2= a - b
res3= np.multiply(a,b)
res4= a/b

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
x = np.sum(a,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1 
y= np.sum(a,axis=1)


In [ ]:
# Write a NumPy function to reverse the array 'a' 
w = np.flip(a)
# Write a NumPy function to reverse the array 'a' along axis=0
v = np.flip(a,axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
u = np.flip(a,axis=1)


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 
t=np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
s=a.sort(axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
r=a.sort(axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
r= np.sort(a)
r=np.flip(a)

In [ ]:
# Write a NumPy function to argsort the array along axis=0
r= np.argsort(a,axis=0)
# Write a NumPy function to argsort the array along axis=1
r= np.argsort(a,axis=1)


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
r= np.concatenate((a,b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
r= np.concatenate((a,b),axis=0)
# Note: You can do the same function using stacking, discover and try that :)
r= np.stack((a,b),axis=0)

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array  
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
newa= a.reshape(1,9)

In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 
r = np.expand_dims(a,axis=0)
r = np.expand_dims(a,axis=1)

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
for x in np.nditer(a) :
  if x > 4 :
    print(x)
  else :
    pass
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
for x in np.nditer(a) :
  if x>4 and x%2 ==0:
    print(x)
  else :
    pass



6
8
5
6
8


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
x = a.copy()
y = np.ones([3,3],dtype=int)

x = x + y
print(x)
  


[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd
df = pd.DataFrame(iris_2d, columns = ['Column_A','Column_B','Column_C','Column_D'])
print(df)
df.dropna(0)








     Column_A  Column_B  Column_C  Column_D
0         5.1       3.5       1.4       0.2
1         4.9       3.0       1.4       0.2
2         4.7       3.2       1.3       0.2
3         4.6       3.1       1.5       0.2
4         5.0       3.6       1.4       0.2
..        ...       ...       ...       ...
145       6.7       3.0       5.2       2.3
146       6.3       2.5       5.0       1.9
147       6.5       3.0       5.2       2.0
148       6.2       3.4       5.4       2.3
149       5.9       3.0       5.1       1.8

[150 rows x 4 columns]


<ipython-input-11-deabc2b675e2>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  df.dropna(0)


Column_A  Column_B  Column_C  Column_D
0         5.1       3.5       1.4       0.2
1         4.9       3.0       1.4       0.2
2         4.7       3.2       1.3       0.2
3         4.6       3.1       1.5       0.2
4         5.0       3.6       1.4       0.2
..        ...       ...       ...       ...
145       6.7       3.0       5.2       2.3
146       6.3       2.5       5.0       1.9
147       6.5       3.0       5.2       2.0
148       6.2       3.4       5.4       2.3
149       5.9       3.0       5.1       1.8

[150 rows x 4 columns]

In [ ]:
# Write a Pandas function to find the correlation between the first two col
col1, col2 = "Column_A" , "Column_B"
df[col1].corr(df[col2])

-0.10936924995064937

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df[['Column_C']].mean(axis=0)
df[['Column_C']].mode()
df[['Column_C']].median()

Column_C    4.35
dtype: float64

In [42]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df['Column_D']= ((mt.pi) * df['Column_C'] * df['Column_A'] * df['Column_A'])/3.0

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.ones(4,dtype=int)
x

array([1, 1, 1, 1])

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])
a = x[:4]
b = x[4:6]
c = x[6:]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = random.randint(100,size = (2,5))
max = np.max(x,axis=1)
mint = np.min(x,axis=1)
print(max)
print(mint)
print(x)

[93 37]
[26  1]
[[77 67 78 93 26]
 [37 20 15 37  1]]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [41]:
dl = pd.DataFrame(iris, columns = names)
print(dl)
dl = dl.dropna()
x = dl['species'].nunique()
print(x)
 

    sepallength sepalwidth petallength petalwidth            species
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'
..          ...        ...         ...        ...                ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]
3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [49]:
for index, x in df.iterrows() :

  if x['Column_C'] > 5 :
    print('large')
  elif x['Column_C']<5 and x['Column_C']>3 :
    print('medium')
  else :
    print('small')
  

  


small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
small
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
small
medium
medium
medium
medium
medium
large
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
medium
small
medium
large
large
large
large
large
large
medium
large
large
large
large
large
large
small
large
large
large
large
large
small
large
medium
large
medium
large
large
medium
medium
large
large
large
large
large
large
large
large
large
large
medium
large
large
large
large
large
large
large
small
large
large
large


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [44]:
dl[['petallength']].mode()

petallength
0      b'1.5'