Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [1]:
import numpy as np
import pandas as pd
import random
import math as mt

In [71]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
a = np.array([1, 2, 3, 4, 5])
print(a)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
b = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
print(b)

[1 2 3 4 5]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [72]:
# Write a NumPy function to create an array with random values of shape [3,4]
x = np.random.random(12).reshape(3, 4)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
y = np.zeros([3, 4])
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
z = np.ones([3, 4])
print(x)
print(y)
print(z)

[[0.55995739 0.9654391  0.5638427  0.60951866]
 [0.06526261 0.54815575 0.66090393 0.40913137]
 [0.79105482 0.75431945 0.91444088 0.18087557]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [73]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


### Basic array operations
- algebraic operations 
- logical operations

In [10]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [11]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
s = (a + b)
d = (a - b)
m = (a * b)
q = (a/b)
print(s)
print(d)
print(m)
print(q)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [12]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
def sum0(a):
  return np.sum(a, axis = 0)
# Write a NumPy function to get the sum of the array 'a' along axis=1 
def sum1(a):
  return np.sum(a, axis = 1)
print(sum0(a))
print(sum1(a))

[ 6 17 14]
[10 13 14]


In [17]:
# Write a NumPy function to reverse the array 'a' 
print(np.flip(a))
# Write a NumPy function to reverse the array 'a' along axis=0
print(np.flip(a, axis = 0))
# Write a NumPy function to reverse the array 'a' along axis=1
print(np.flip(a, axis = 1))

[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]]
[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [18]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [19]:
# Write a NumPy function to sort the array 'a' 
def sor(a):
  return np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
def sort0(a):
  return np.sort(a, axis = 0)
# Write a NumPy function to sort the array 'a' along axis=1
def sort1(a):
  return np.sort(a, axis = 1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def revsort0(a):
  return -np.sort(-a, axis = 0)
print(sor(a))
print(sort0(a))
print(sort1(a))
print(revsort0(a))

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [20]:
# Write a NumPy function to argsort the array along axis=0
def arsort(a):
  return np.argsort(a, axis = 0)
# Write a NumPy function to argsort the array along axis=1
def arsort1(a):
  return np.argsort(a, axis = 1)
print(arsort(a))
print(arsort1(a))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [21]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def ccat(a, b):
  return np.concatenate((a, b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def ccat0(a, b):
  return np.concatenate((a, b), axis = 0)
# Note: You can do the same function using stacking, discover and try that :)
print(ccat(a, b))
print(ccat0(a, b))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [22]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [23]:
# Write a NumPy function to get the Number of dimensions
print(np.ndim(a))
# Write a NumPy function to get the Shape of the array  
print(np.shape(a))
# Write a NumPy function to get the Size of the array
print(np.size(a))

2
(3, 3)
9


In [24]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(a.reshape(1, 9))

[[4 6 8 9 3 1 1 8 5]]


In [25]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 
a = a[np.newaxis]
print(a)

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [65]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [27]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
c = (0, 2)
d = (1, 2)
b = a[1:2, 0:2]
e = a[c, d]
print(b)
print(e)

[[0 3]]
[6 5]


In [67]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
print(a > 4)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

for i in range(0, 3):
  for j in range(0, 3):
    if ((a[i][j] > 4) and (a[i][j] % 2 == 0)):
      a[i][j] = True
    else:
      a[i][j] = False
      
print(a)

[[False  True False]
 [False False False]
 [False  True  True]]
[[0 1 0]
 [0 0 0]
 [0 1 0]]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [29]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [32]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b = a + np.ones([np.ndim(a) + 1, len(a[0])])
print(b)

[[5. 7. 1.]
 [1. 4. 2.]
 [2. 9. 6.]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [3]:
# Write a Pandas function to drop rows that contain a missing value. 
print(pd.DataFrame(iris_2d).dropna())

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [4]:
# Write a Pandas function to find the correlation between the first two columns.
data = pd.DataFrame(iris_2d)
print(data.corr()[0][1])

-0.10936924995064931


In [38]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
data = pd.DataFrame(iris_2d)
print(data.mean()[2])
print(data.median()[2])
print(data.std()[2])

3.7586666666666693
4.35
1.7644204199522626


In [5]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
data = pd.DataFrame(iris_2d)
ar = []
for i in range(0, len(data)):
    ar.append((mt.pi * data.loc[i][2] * (data.loc[i][0])**2)/float(3))
data['Volume'] = ar
print(data)

       0    1    2    3      Volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [43]:
y = [0, 1, 2, 3]
print(y)

[0, 1, 2, 3]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [45]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a = x[:4]
b = x[4:6]
c = x[6:]
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [49]:
 x = np.random.randint(0, 10, 10).reshape(2, 5)
 maxArr = np.max(x, axis = 1)
 minArr = np.min(x, axis = 1)
 print(maxArr)
 print(minArr)

[8 8]
[1 2]


### Pandas

Run the following load command and solve the following questions

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [7]:
ar = []
count = 0
df = pd.DataFrame(iris, columns = names)
df = df.dropna()
for i in range(0, len(df)):
  if df['species'][i] not in ar:
    ar.append(df['species'][i])
    count += 1
print(df)
print(count)

    sepallength sepalwidth petallength petalwidth            species
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'
..          ...        ...         ...        ...                ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]
3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [8]:
s = []
for i in range(0, len(df)):
  if float(df["petallength"][i].decode()) < 3.0:
    s.append("small")
  if float(df["petallength"][i].decode()) >=5.0:
    s.append("large")
  else:
    s.append("medium")
print(s)

['small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium',

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [60]:
print(float(df.mode()["petallength"][0].decode()))

1.5
